import {
  Search,
  Menu,
  X,
  Sun,
  Moon,
  User,
  Play,
  Plus,
  Check,
  CheckCircle,
  ChevronLeft,
  ChevronRight,
  ChevronDown,
  Home,
  Film,
  Tv,
  Sparkles,
  Heart,
  Star,
  Clock,
  Settings,
  LogOut,
  Globe,
  Volume2,
  VolumeX,
  Maximize,
  Minimize,
  SkipBack,
  SkipForward,
  Pause,
  Info,
  Loader2,
  Bell,
  Share2,
  UserPlus,
  UserMinus,
  MessageCircle,
  List,
  Trash2,
  Edit,
  Send,
  Copy,
  ExternalLink,
  PictureInPicture2,
  Users,
  Shield,
  BarChart3,
  Subtitles,
  Monitor,
  Clapperboard,
  Crown,
  CreditCard,
  RefreshCw,
  AlertCircle,
  Mail,
  Award,
  Calendar,
  Gift,
  Eye,
  FolderOpen,
  Compass,
  LayoutDashboard,
  Flag,
  MessageSquare,
  HelpCircle,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  ShieldAlert,
  Activity,
  ShieldCheck,
  AlertTriangle,
  Ban,
  Zap,
  UserX,
  Layers,
  Lock,
  UserCheck,
  Lightbulb,
  Download,
  Pin,
  PinOff,
  Reply
} from 'lucide-react'

export const Icons = {
  search: Search,
  menu: Menu,
  close: X,
  x: X,
  sun: Sun,
  moon: Moon,
  user: User,
  play: Play,
  pause: Pause,
  plus: Plus,
  check: Check,
  checkCircle: CheckCircle,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  chevronDown: ChevronDown,
  film: Film,
  tv: Tv,
  anime: Sparkles,
  heart: Heart,
  star: Star,
  clock: Clock,
  settings: Settings,
  logout: LogOut,
  globe: Globe,
  volumeOn: Volume2,
  volumeOff: VolumeX,
  fullscreen: Maximize,
  exitFullscreen: Minimize,
  skipBack: SkipBack,
  skipForward: SkipForward,
  info: Info,
  spinner: Loader2,
  bell: Bell,
  share: Share2,
  follow: UserPlus,
  unfollow: UserMinus,
  comment: MessageCircle,
  messageCircle: MessageCircle,
  list: List,
  trash: Trash2,
  edit: Edit,
  send: Send,
  copy: Copy,
  externalLink: ExternalLink,
  pip: PictureInPicture2,
  users: Users,
  shield: Shield,
  chart: BarChart3,
  subtitles: Subtitles,
  monitor: Monitor,
  clapperboard: Clapperboard,
  crown: Crown,
  creditCard: CreditCard,
  refresh: RefreshCw,
  alertCircle: AlertCircle,
  mail: Mail,
  userPlus: UserPlus,
  award: Award,
  calendar: Calendar,
  gift: Gift,
  eye: Eye,
  // Yeni eklenenler
  folderOpen: FolderOpen,
  compass: Compass,
  dashboard: LayoutDashboard,
  flag: Flag,
  messageSquare: MessageSquare,
  help: HelpCircle,
  arrowLeft: ArrowLeft,
  arrowRight: ArrowRight,
  arrowUp: ArrowUp,
  shieldAlert: ShieldAlert,
  activity: Activity,
  shieldCheck: ShieldCheck,
  alertTriangle: AlertTriangle,
  ban: Ban,
  zap: Zap,
  userX: UserX,
  layers: Layers,
  lock: Lock,
  home: Home,
  userCheck: UserCheck,
  lightbulb: Lightbulb,
  download: Download,
  pin: Pin,
  pinOff: PinOff,
  reply: Reply
}

export type IconName = keyof typeof Icons
